'use client'

import { useEffect, useState, useCallback } from 'react'
import { FileText, RefreshCw, Trash2, Loader2, Download, Printer, CheckCircle } from 'lucide-react'
import { PageHeader } from '@/components/ui/PageHeader'
import { AlertBadge } from '@/components/ui/AlertBadge'
import { MONTHS, type Month } from '@/lib/filter-types'

interface MonthlyReport {
  id: string
  businessUnit: string
  year: number
  month: string
  generatedAt: string
  reportData: string
  narrative: string
  generatedBy?: string | null
}

interface BU { id: string; name: string }

function fmt(dt: string) {
  return new Date(dt).toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })
}

export default function ReportsPage() {
  const [reports, setReports] = useState<MonthlyReport[]>([])
  const [busUnits, setBusUnits] = useState<BU[]>([])
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState<string | null>(null)
  const [deleting, setDeleting] = useState<string | null>(null)
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear())
  const [filterBU, setFilterBU] = useState('ALL')
  const [generatedBy, setGeneratedBy] = useState('L&D Administrator')

  const currentYear = new Date().getFullYear()
  const availableYears = Array.from({ length: 5 }, (_, i) => currentYear - 1 + i)
  const currentMonthIdx = new Date().getMonth()

  const load = useCallback(async () => {
    setLoading(true)
    try {
      const [repRes, buRes] = await Promise.all([
        fetch(`/api/reports?year=${selectedYear}${filterBU !== 'ALL' ? `&bu=${encodeURIComponent(filterBU)}` : ''}`),
        fetch('/api/business-units'),
      ])
      setReports(await repRes.json())
      setBusUnits(await buRes.json())
    } finally {
      setLoading(false)
    }
  }, [selectedYear, filterBU])

  useEffect(() => { load() }, [load])

  const reportKey = (bu: string, month: string) => `${bu}||${month}`
  const reportMap = new Map(reports.map((r) => [reportKey(r.businessUnit, r.month), r]))

  const allBUs = ['GROUP', ...busUnits.map((b) => b.name)]
  const visibleBUs = filterBU === 'ALL' ? allBUs : [filterBU]

  const generate = async (bu: string, month: string) => {
    const key = `${bu}_${month}_${selectedYear}`
    setGenerating(key)
    try {
      await fetch('/api/reports', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ businessUnit: bu, year: selectedYear, month, generatedBy }),
      })
      await load()
    } finally {
      setGenerating(null)
    }
  }

  const deleteReport = async (id: string) => {
    if (!confirm('Delete this report snapshot?')) return
    setDeleting(id)
    try {
      await fetch(`/api/reports?id=${id}`, { method: 'DELETE' })
      await load()
    } finally {
      setDeleting(null)
    }
  }

  const downloadPDF = (report: MonthlyReport) => {
    const prev = document.title
    document.title = `${report.businessUnit} — ${report.month} ${report.year} Report`
    window.print()
    document.title = prev
  }

  const downloadExcel = async (report: MonthlyReport) => {
    const data = JSON.parse(report.reportData ?? '{}')
    const XLSXmod = await import('xlsx')
    const XLSX = XLSXmod.default ?? XLSXmod
    const wb = XLSX.utils.book_new()

    // Summary sheet
    const summary = [
      { Metric: 'Business Unit', Value: report.businessUnit },
      { Metric: 'Period', Value: `${report.month} ${report.year}` },
      { Metric: 'Generated', Value: fmt(report.generatedAt) },
      { Metric: 'Generated By', Value: report.generatedBy ?? '' },
      { Metric: '', Value: '' },
      { Metric: 'Narrative', Value: report.narrative },
    ]
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(summary), 'Summary')

    // BU data if available
    if (data.topTrainings?.length) {
      XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(
        data.topTrainings.map((t: { training: string; count: number; totalCost: number }) => ({
          Programme: t.training, Participants: t.count, 'Total Cost (₦)': t.totalCost,
        }))
      ), 'Training Programmes')
    }
    if (data.monthlySpend?.length) {
      XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(
        data.monthlySpend.map((m: { month: string; cost: number }) => ({ Month: m.month, 'Cost (₦)': m.cost }))
      ), 'Monthly Spend')
    }

    XLSX.writeFile(wb, `${report.businessUnit.replace(/\s+/g, '_')}_${report.month}_${report.year}.xlsx`)
  }

  return (
    <div className="flex flex-col">
      <PageHeader
        title="Report Generation & History"
        subtitle="Generate and download monthly learning reports per business unit"
        actions={
          <button onClick={load} className="flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-800">
            <RefreshCw className="w-3.5 h-3.5" /> Refresh
          </button>
        }
      />

      <div className="p-8 space-y-6">
        {/* Controls */}
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-5 space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs font-semibold text-slate-600 uppercase tracking-wider mb-2">Report Year</label>
              <select
                value={selectedYear}
                onChange={(e) => setSelectedYear(parseInt(e.target.value))}
                className="w-full text-sm border border-slate-200 rounded-lg px-3 py-2.5 focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                {availableYears.map((y) => (
                  <option key={y} value={y}>{y}{y === currentYear ? ' (current)' : ''}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-600 uppercase tracking-wider mb-2">Filter Business Unit</label>
              <select
                value={filterBU}
                onChange={(e) => setFilterBU(e.target.value)}
                className="w-full text-sm border border-slate-200 rounded-lg px-3 py-2.5 focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="ALL">All Business Units</option>
                <option value="GROUP">Group (Organisation-wide)</option>
                {busUnits.map((b) => <option key={b.id} value={b.name}>{b.name}</option>)}
              </select>
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-600 uppercase tracking-wider mb-2">Generated By</label>
              <input
                type="text"
                value={generatedBy}
                onChange={(e) => setGeneratedBy(e.target.value)}
                className="w-full text-sm border border-slate-200 rounded-lg px-3 py-2.5 focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Administrator name"
              />
            </div>
          </div>
          <p className="text-xs text-slate-400">
            Months up to {MONTHS[currentMonthIdx]} {currentYear} are available for generation. Future months will use current data as a projection.
          </p>
        </div>

        {loading ? (
          <div className="flex items-center gap-3 text-sm text-slate-500 py-8 justify-center">
            <Loader2 className="w-5 h-5 animate-spin" /> Loading reports…
          </div>
        ) : (
          <>
            {/* Report grid per BU */}
            {visibleBUs.map((bu) => (
              <div key={bu} className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
                {/* BU header */}
                <div className="flex items-center gap-3 px-5 py-4 border-b border-slate-100 bg-slate-50">
                  <FileText className="w-4 h-4 text-slate-400" />
                  <p className="text-sm font-bold text-slate-800">{bu === 'GROUP' ? 'Organisation (Group)' : bu}</p>
                  <span className="text-xs text-slate-400 ml-auto">
                    {reports.filter((r) => r.businessUnit === bu && r.year === selectedYear).length} of {MONTHS.length} months generated
                  </span>
                </div>

                {/* Month grid */}
                <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 gap-0 divide-x divide-y divide-slate-100">
                  {MONTHS.map((month, idx) => {
                    const existing = reportMap.get(reportKey(bu, month))
                    const genKey = `${bu}_${month}_${selectedYear}`
                    const isGenerating = generating === genKey
                    const isFuture = idx > currentMonthIdx && selectedYear === currentYear

                    return (
                      <div key={month} className={`p-4 ${isFuture ? 'bg-slate-50/50' : 'bg-white'}`}>
                        <div className="flex items-start justify-between mb-2">
                          <p className="text-xs font-semibold text-slate-700">{month.slice(0, 3)}</p>
                          {existing && (
                            <CheckCircle className="w-3.5 h-3.5 text-green-500 shrink-0" />
                          )}
                        </div>

                        {existing ? (
                          <div className="space-y-1.5">
                            <p className="text-[10px] text-slate-400 leading-tight">{fmt(existing.generatedAt)}</p>
                            <div className="flex gap-1 flex-wrap">
                              <button
                                onClick={() => downloadPDF(existing)}
                                title="Export PDF"
                                className="flex items-center gap-1 text-[10px] px-1.5 py-1 rounded bg-blue-50 text-blue-600 hover:bg-blue-100 transition-colors font-medium"
                              >
                                <Printer className="w-2.5 h-2.5" /> PDF
                              </button>
                              <button
                                onClick={() => downloadExcel(existing)}
                                title="Export Excel"
                                className="flex items-center gap-1 text-[10px] px-1.5 py-1 rounded bg-green-50 text-green-600 hover:bg-green-100 transition-colors font-medium"
                              >
                                <Download className="w-2.5 h-2.5" /> XLS
                              </button>
                              <button
                                onClick={() => deleteReport(existing.id)}
                                disabled={deleting === existing.id}
                                className="p-1 text-slate-300 hover:text-red-500 transition-colors"
                                title="Delete"
                              >
                                <Trash2 className="w-2.5 h-2.5" />
                              </button>
                            </div>
                            {/* Re-generate */}
                            <button
                              onClick={() => generate(bu, month)}
                              disabled={isGenerating}
                              className="text-[10px] text-blue-500 hover:text-blue-700 font-medium"
                            >
                              {isGenerating ? <Loader2 className="w-3 h-3 animate-spin inline" /> : '↻ Regenerate'}
                            </button>
                          </div>
                        ) : (
                          <button
                            onClick={() => generate(bu, month)}
                            disabled={isGenerating}
                            className={`w-full mt-1 flex items-center justify-center gap-1 text-[10px] py-1.5 rounded-lg font-semibold transition-colors ${
                              isFuture
                                ? 'bg-slate-100 text-slate-400 cursor-not-allowed'
                                : 'bg-blue-50 text-blue-600 hover:bg-blue-100'
                            }`}
                          >
                            {isGenerating ? <Loader2 className="w-3 h-3 animate-spin" /> : '+ Generate'}
                          </button>
                        )}
                      </div>
                    )
                  })}
                </div>
              </div>
            ))}
          </>
        )}

        {/* History table */}
        {reports.length > 0 && (
          <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="px-5 py-4 border-b border-slate-100">
              <p className="text-sm font-bold text-slate-800">Generation History — {selectedYear}</p>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-slate-50 border-b border-slate-200">
                    {['Business Unit', 'Month', 'Generated At', 'Generated By', 'Actions'].map((h) => (
                      <th key={h} className="px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider text-left">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {reports.sort((a, b) => MONTHS.indexOf(b.month as typeof MONTHS[number]) - MONTHS.indexOf(a.month as typeof MONTHS[number])).map((r) => (
                    <tr key={r.id} className="hover:bg-slate-50">
                      <td className="px-4 py-3 font-medium text-slate-800">{r.businessUnit === 'GROUP' ? 'Organisation (Group)' : r.businessUnit}</td>
                      <td className="px-4 py-3 text-slate-600">{r.month} {r.year}</td>
                      <td className="px-4 py-3 text-slate-500 text-xs">{fmt(r.generatedAt)}</td>
                      <td className="px-4 py-3 text-slate-500 text-xs">{r.generatedBy ?? '—'}</td>
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-2">
                          <button onClick={() => downloadPDF(r)} className="flex items-center gap-1 text-xs px-2 py-1 rounded bg-blue-50 text-blue-600 hover:bg-blue-100 font-medium">
                            <Printer className="w-3 h-3" /> PDF
                          </button>
                          <button onClick={() => downloadExcel(r)} className="flex items-center gap-1 text-xs px-2 py-1 rounded bg-green-50 text-green-600 hover:bg-green-100 font-medium">
                            <Download className="w-3 h-3" /> Excel
                          </button>
                          <button
                            onClick={() => deleteReport(r.id)}
                            disabled={deleting === r.id}
                            className="p-1 text-slate-400 hover:text-red-600 transition-colors"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {reports.length === 0 && !loading && (
          <AlertBadge variant="info" message={`No reports generated for ${selectedYear} yet. Click "+ Generate" on any month above to create your first snapshot.`} />
        )}
      </div>
    </div>
  )
}
